language: python
python:
  - "3.7"
before_install:
  - python --version
install:
  - pip install -r requirements.txt
  - pip install --upgrade pytest
script:
  - pytest -v --cov=./
after_success:
  - codecov
